/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import edd_proyecto_1_jecklin_vergel_vivas.ColoniaHormigas;
import java.util.Random;
import javax.swing.JOptionPane;
  
/**
 *
 * @author Edward Vergel
 */
public class iniciarSimulacion extends javax.swing.JFrame {
    ColoniaHormigas ch = new ColoniaHormigas();
    Random rand = new Random();
    int cantidadHormigas;
    int Alpha;
    int Betta;
    int iteraciones;
    double Rho;
    
    /**
     * Creates new form iniciarSimulacion
     */
    public iniciarSimulacion() {
        this.cantidadHormigas = 0;
        this.Alpha = 0;
        this.Betta = 0;
        this.iteraciones = 0;
        this.Rho = 0.0;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        defaultRho = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CantidadHormigas = new javax.swing.JSlider();
        defaultIteraciones = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        cantidadIteraciones = new javax.swing.JSlider();
        defaultAlpha = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        cantidadAlpha = new javax.swing.JSlider();
        HormigasDefault = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        cantidadBetta = new javax.swing.JSlider();
        defaultBetta1 = new javax.swing.JRadioButton();
        showRho = new javax.swing.JTextField();
        showHormigas = new javax.swing.JTextField();
        showIteraciones = new javax.swing.JTextField();
        showAlpha = new javax.swing.JTextField();
        showBetta = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setFocusable(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        defaultRho.setBackground(new java.awt.Color(255, 255, 255));
        defaultRho.setForeground(new java.awt.Color(0, 0, 0));
        defaultRho.setText("Rho Default");
        defaultRho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defaultRhoActionPerformed(evt);
            }
        });
        jPanel1.add(defaultRho, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 110, -1));

        jLabel1.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Rho:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, 30));

        jLabel2.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Cantidad de Hormigas:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 160, 30));

        CantidadHormigas.setBackground(new java.awt.Color(204, 204, 204));
        CantidadHormigas.setForeground(new java.awt.Color(0, 0, 0));
        CantidadHormigas.setMajorTickSpacing(25);
        CantidadHormigas.setMaximum(200);
        CantidadHormigas.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                CantidadHormigasStateChanged(evt);
            }
        });
        jPanel1.add(CantidadHormigas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        defaultIteraciones.setBackground(new java.awt.Color(255, 255, 255));
        defaultIteraciones.setForeground(new java.awt.Color(0, 0, 0));
        defaultIteraciones.setText("Valor Default");
        defaultIteraciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defaultIteracionesActionPerformed(evt);
            }
        });
        jPanel1.add(defaultIteraciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 140, -1));

        jLabel3.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Cantidad de Iteraciones:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, 30));

        cantidadIteraciones.setBackground(new java.awt.Color(204, 204, 204));
        cantidadIteraciones.setForeground(new java.awt.Color(0, 0, 0));
        cantidadIteraciones.setMajorTickSpacing(25);
        cantidadIteraciones.setMaximum(500);
        cantidadIteraciones.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cantidadIteracionesStateChanged(evt);
            }
        });
        jPanel1.add(cantidadIteraciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        defaultAlpha.setBackground(new java.awt.Color(255, 255, 255));
        defaultAlpha.setForeground(new java.awt.Color(0, 0, 0));
        defaultAlpha.setText("Alpha Default");
        defaultAlpha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defaultAlphaActionPerformed(evt);
            }
        });
        jPanel1.add(defaultAlpha, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 110, -1));

        jLabel4.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Alpha");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 30));

        cantidadAlpha.setBackground(new java.awt.Color(204, 204, 204));
        cantidadAlpha.setForeground(new java.awt.Color(0, 0, 0));
        cantidadAlpha.setMajorTickSpacing(1);
        cantidadAlpha.setMaximum(20);
        cantidadAlpha.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cantidadAlphaStateChanged(evt);
            }
        });
        jPanel1.add(cantidadAlpha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        HormigasDefault.setBackground(new java.awt.Color(255, 255, 255));
        HormigasDefault.setForeground(new java.awt.Color(0, 0, 0));
        HormigasDefault.setText("Hormigas Default");
        HormigasDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HormigasDefaultActionPerformed(evt);
            }
        });
        jPanel1.add(HormigasDefault, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 140, -1));

        jLabel5.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Betta:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, 30));

        cantidadBetta.setBackground(new java.awt.Color(204, 204, 204));
        cantidadBetta.setForeground(new java.awt.Color(0, 0, 0));
        cantidadBetta.setMajorTickSpacing(1);
        cantidadBetta.setMaximum(20);
        cantidadBetta.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cantidadBettaStateChanged(evt);
            }
        });
        jPanel1.add(cantidadBetta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        defaultBetta1.setBackground(new java.awt.Color(255, 255, 255));
        defaultBetta1.setForeground(new java.awt.Color(0, 0, 0));
        defaultBetta1.setText("Betta Default");
        defaultBetta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defaultBetta1ActionPerformed(evt);
            }
        });
        jPanel1.add(defaultBetta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 110, -1));

        showRho.setBackground(new java.awt.Color(255, 255, 255));
        showRho.setToolTipText("Introduzca Rho");
        showRho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showRhoActionPerformed(evt);
            }
        });
        jPanel1.add(showRho, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 100, -1));

        showHormigas.setEditable(false);
        showHormigas.setBackground(new java.awt.Color(255, 255, 255));
        showHormigas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showHormigasActionPerformed(evt);
            }
        });
        jPanel1.add(showHormigas, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 60, -1));

        showIteraciones.setEditable(false);
        showIteraciones.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(showIteraciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 60, -1));

        showAlpha.setEditable(false);
        showAlpha.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(showAlpha, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 60, -1));

        showBetta.setEditable(false);
        showBetta.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(showBetta, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 60, -1));

        jButton1.setText("COMENZAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 130, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void defaultRhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defaultRhoActionPerformed
        if (this.defaultRho.isSelected()){
            Rho = 0.5;
            this.showRho.setText("0.5");
            this.showRho.setEnabled(false);
        }else {
        this.showRho.setEnabled(true);
        }
    }//GEN-LAST:event_defaultRhoActionPerformed

    private void defaultIteracionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defaultIteracionesActionPerformed
        if (this.defaultIteraciones.isSelected()){
            iteraciones = 10;
            this.showIteraciones.setText("10");
            this.cantidadIteraciones.setEnabled(false);
        }else {
        this.cantidadIteraciones.setEnabled(true);
        }
    }//GEN-LAST:event_defaultIteracionesActionPerformed

    private void defaultAlphaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defaultAlphaActionPerformed
        if (this.defaultAlpha.isSelected()){
            Alpha = 1;
            this.showAlpha.setText("1");
            this.cantidadAlpha.setEnabled(false);
        }else {
            this.cantidadAlpha.setEnabled(true);
        }
    }//GEN-LAST:event_defaultAlphaActionPerformed

    private void HormigasDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HormigasDefaultActionPerformed
        if (this.HormigasDefault.isSelected()){
            cantidadHormigas = 5;
            this.showHormigas.setText("5");
            this.CantidadHormigas.setEnabled(false);
        }else {
            this.CantidadHormigas.setEnabled(true);
        }
    }//GEN-LAST:event_HormigasDefaultActionPerformed

    private void defaultBetta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defaultBetta1ActionPerformed
        if (this.defaultBetta1.isSelected()){
            Betta = 2;
            this.showBetta.setText("2");
            this.cantidadBetta.setEnabled(false);
        }else{
            this.cantidadBetta.setEnabled(true);
        }
    }//GEN-LAST:event_defaultBetta1ActionPerformed

    private void showHormigasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showHormigasActionPerformed
        
    }//GEN-LAST:event_showHormigasActionPerformed

    private void CantidadHormigasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_CantidadHormigasStateChanged

        showHormigas.setText(String.valueOf(CantidadHormigas.getValue()));
        cantidadHormigas = CantidadHormigas.getValue();
        if (this.HormigasDefault.isSelected()){
            cantidadHormigas = 20;
            this.CantidadHormigas.setValue(20);
        }
    }//GEN-LAST:event_CantidadHormigasStateChanged

    private void cantidadIteracionesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cantidadIteracionesStateChanged

        showIteraciones.setText(String.valueOf(cantidadIteraciones.getValue()));
        iteraciones = cantidadIteraciones.getValue();
        if (this.defaultIteraciones.isSelected()){
            iteraciones = 50;
            this.cantidadIteraciones.setValue(50);
        }
    }//GEN-LAST:event_cantidadIteracionesStateChanged

    private void cantidadAlphaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cantidadAlphaStateChanged

        showAlpha.setText(String.valueOf(cantidadAlpha.getValue()));
        Alpha = cantidadAlpha.getValue();
        if (this.defaultAlpha.isSelected()){
            Alpha = 1;
            this.cantidadAlpha.setValue(1);
        }
    }//GEN-LAST:event_cantidadAlphaStateChanged

    private void cantidadBettaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cantidadBettaStateChanged

        showBetta.setText(String.valueOf(cantidadBetta.getValue()));
        Betta = cantidadBetta.getValue();
        if (this.defaultBetta1.isSelected()){
            Betta = 2;
            this.cantidadBetta.setValue(2);
        }
    }//GEN-LAST:event_cantidadBettaStateChanged

    private void showRhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showRhoActionPerformed

        try{
            String sRho = this.showRho.getText();
            Rho = Double.parseDouble(sRho);
            if (this.defaultRho.isSelected()){
            Rho = 0.5;
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"ERROR: RHO INVALIDO");
        }
    }//GEN-LAST:event_showRhoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Resultados r = new Resultados();
        if(Rho == 0){
            JOptionPane.showMessageDialog(null, "ADVERTENCIA: INTRODUZCA VALOR A <Rho> Y PRESIONE <ENTER>");
        }
        if(Alpha != 0 && Betta != 0 && cantidadHormigas != 0 && Rho !=0 && iteraciones !=0){
            ch.cerebro(rand, iteraciones, Rho, Alpha, Betta, cantidadHormigas);
            r.setVisible(true);
            dispose();
        }else {
            JOptionPane.showMessageDialog(null, "ERROR: FALTAN INICIALIZAR VALORES");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(iniciarSimulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(iniciarSimulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(iniciarSimulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(iniciarSimulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new iniciarSimulacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider CantidadHormigas;
    private javax.swing.JRadioButton HormigasDefault;
    private javax.swing.JSlider cantidadAlpha;
    private javax.swing.JSlider cantidadBetta;
    private javax.swing.JSlider cantidadIteraciones;
    private javax.swing.JRadioButton defaultAlpha;
    private javax.swing.JRadioButton defaultBetta1;
    private javax.swing.JRadioButton defaultIteraciones;
    private javax.swing.JRadioButton defaultRho;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField showAlpha;
    private javax.swing.JTextField showBetta;
    private javax.swing.JTextField showHormigas;
    private javax.swing.JTextField showIteraciones;
    private javax.swing.JTextField showRho;
    // End of variables declaration//GEN-END:variables
}
