/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import edd_proyecto_1_Fernandez_vergel_vivas.Funciones;
import edd_proyecto_1_Fernandez_vergel_vivas.ListaCiudades;
import javax.swing.JOptionPane;

/**
 *
 * @author Edward Vergel
 */
public class menuPrincipal extends javax.swing.JFrame {

    Funciones f;
    ListaCiudades ciudades;
    double[][] mcosto;

    public menuPrincipal() {
        initComponents();
        f = new Funciones();
        this.setLocationRelativeTo(null);
        this.CiudadesEnSimulacion.setEditable(false);
        String[] list = f.cargarDatos();
        ciudades = f.obtenerCiudades(list);
        f.invertirArreglo(list);
        int n = ciudades.getTamanio();
        mcosto = f.obtenerCosto(list, n);
        String ciudad = "";

        for (int i = 0; i < n; i++) {
            ciudad += i + "." + ciudades.obtenerCiudadIndex(i).getNombre() + "\n";
        }

        this.CiudadesEnSimulacion.setText(ciudad);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nuevaSimulacion = new javax.swing.JButton();
        cargarGrafo = new javax.swing.JButton();
        insertarCiudad = new javax.swing.JButton();
        eliminarCiudad = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        CiudadesEnSimulacion = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nuevaSimulacion.setBackground(new java.awt.Color(51, 51, 51));
        nuevaSimulacion.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        nuevaSimulacion.setForeground(new java.awt.Color(255, 255, 255));
        nuevaSimulacion.setText("Empezar Simulacion");
        nuevaSimulacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaSimulacionActionPerformed(evt);
            }
        });
        jPanel1.add(nuevaSimulacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 160, 40));

        cargarGrafo.setBackground(new java.awt.Color(51, 51, 51));
        cargarGrafo.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        cargarGrafo.setForeground(new java.awt.Color(255, 255, 255));
        cargarGrafo.setText("Cargar");
        cargarGrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarGrafoActionPerformed(evt);
            }
        });
        jPanel1.add(cargarGrafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 160, 30));

        insertarCiudad.setBackground(new java.awt.Color(51, 51, 51));
        insertarCiudad.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        insertarCiudad.setForeground(new java.awt.Color(255, 255, 255));
        insertarCiudad.setText("Insertar Ciudad");
        insertarCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertarCiudadActionPerformed(evt);
            }
        });
        jPanel1.add(insertarCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 160, 40));

        eliminarCiudad.setBackground(new java.awt.Color(51, 51, 51));
        eliminarCiudad.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        eliminarCiudad.setForeground(new java.awt.Color(255, 255, 255));
        eliminarCiudad.setText("Eliminar Ciudad");
        eliminarCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarCiudadActionPerformed(evt);
            }
        });
        jPanel1.add(eliminarCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 160, 40));

        jLabel3.setFont(new java.awt.Font("Eras Demi ITC", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Ciudades en Simulacion");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, -1));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Eras Demi ITC", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Datos:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(130, 130, 130))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 180, 80));

        exitButton.setBackground(new java.awt.Color(255, 255, 255));
        exitButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        exitButton.setForeground(new java.awt.Color(0, 0, 0));
        exitButton.setText("x");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        jPanel1.add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 50, 30));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ANT ALGORITHM");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 190, 50));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 190, 50));

        CiudadesEnSimulacion.setEditable(false);
        CiudadesEnSimulacion.setBackground(new java.awt.Color(102, 102, 102));
        CiudadesEnSimulacion.setColumns(20);
        CiudadesEnSimulacion.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        CiudadesEnSimulacion.setForeground(new java.awt.Color(255, 255, 255));
        CiudadesEnSimulacion.setRows(5);
        jScrollPane2.setViewportView(CiudadesEnSimulacion);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 350, 160));

        jLabel4.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("*Los datos se guardan automaticamente*");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void nuevaSimulacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevaSimulacionActionPerformed
        iniciarSimulacion is = new iniciarSimulacion(ciudades);
        is.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_nuevaSimulacionActionPerformed

    private void eliminarCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarCiudadActionPerformed
        String ciudad = "";
        String ciudadEliminada = JOptionPane.showInputDialog(null, "Ingrese el ID de la ciudad a eliminar: ");
        if (ciudadEliminada == null) {

        } else {
            if(ciudades.getTamanio()>4){
            int id = Integer.parseInt(ciudadEliminada);
            if (id >= ciudades.getTamanio() || id < 0) {
                JOptionPane.showMessageDialog(null, "ERROR: CIUDAD INEXISTENTE", "ERROR", 0);
            } else {
                double[][] ciudadEl = f.eliminarCiudad(ciudades, mcosto, id, id);
                f.subirDatos(ciudades, ciudadEl);
                JOptionPane.showMessageDialog(null, "CIUDAD ELIMINADA CON EXITO");
                for (int i = 0; i < ciudades.getTamanio(); i++) {
                    ciudad += i + "." + ciudades.obtenerCiudadIndex(i).getNombre() + "\n";
                }
                this.CiudadesEnSimulacion.setText(ciudad);
            }
            }else {
                JOptionPane.showMessageDialog(null, "ERROR: VALOR MINIMO DE CIUDADES ALCANZADO");
            }
        }
    }//GEN-LAST:event_eliminarCiudadActionPerformed

    private void cargarGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarGrafoActionPerformed
        JOptionPane.showMessageDialog(null, "LOS DATOS YA ESTAN CARGADOS", "ADVERTENCIA", 1);
    }//GEN-LAST:event_cargarGrafoActionPerformed

    private void insertarCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarCiudadActionPerformed
         String ciudad = "";
        String ciudadEliminada = JOptionPane.showInputDialog(null, "Ingrese nombre de la ciudad a agregar: ");
        if (ciudadEliminada == null) {
            
        } else {
            
                for (int i = 0; i < ciudades.getTamanio(); i++) {
                    ciudad += i + "." + ciudades.obtenerCiudadIndex(i).getNombre() + "\n";
                }
                this.CiudadesEnSimulacion.setText(ciudad);
            }
           
    }//GEN-LAST:event_insertarCiudadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea CiudadesEnSimulacion;
    private javax.swing.JButton cargarGrafo;
    private javax.swing.JButton eliminarCiudad;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton insertarCiudad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton nuevaSimulacion;
    // End of variables declaration//GEN-END:variables
}
